### ISSUE TITLE
Description: Ticking entity  - java.lang.IllegalAccessError

### ISSUE THREAD

**Issue by jokish63** [airbreather/YAFM#6]
game crashed on start up

crash report: http://paste.ee/p/6tDgE
latest log: http://paste.ee/p/FuG4r

tested with forge 1832 and 1835
for your information
best regards jokish

**Comment by airbreather** [comment]
Yeah it looks like you're going to see that all over the place at least for the time being.  See the comments at the bottom of MinecraftForge/MinecraftForge@756c58d.

I'm not sure if I want to fix this immediately, since Lex said they might write an access transformer to make things "just work".  For the time being, it looks like downgrading your Forge version to no later than build 1804 is what needs to happen.

**Comment by jokish63** [comment]
I can understand you. It seems hard to be a Mod dev at this time.
I think I'm still waiting a little time if forge becomes slightly more stable. 
This gives me time to explore the new 1.9 Vanilla Stuff
I like your mods a lot and for me it is a must to have.
best regards jokish
